name: YaCy CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -yq ant git wkhtmltopdf imagemagick xvfb ghostscript

    - name: Build with Ant
      run: |
        ant compile -f build.xml
        git rev-parse HEAD > .git/shallow
        git tag -l | xargs git tag -d
        git gc --prune=now

    - name: Configure runtime settings
      run: |
        sed -i "/adminAccountBase64MD5=/c\adminAccountBase64MD5=MD5:8cffbc0d66567a0987a4aba1ec46d63c" defaults/yacy.init
        sed -i "/adminAccountForLocalhost=/c\adminAccountForLocalhost=false" defaults/yacy.init
        sed -i "/server.https=false/c\server.https=true" defaults/yacy.init
